# Alternative GNU Make project makefile autogenerated by Premake

ifndef config
  config=releasewithsymbols_x86
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq (.exe,$(findstring .exe,$(ComSpec)))
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

RESCOMP = windres
INCLUDES += -Isrc -IFleX/include -IBSPParser -IGMFS -isystem garrysmod_common/include -isystem garrysmod_common/helpers/include -isystem garrysmod_common/scanning/include -isystem garrysmod_common/detouring/include -isystem garrysmod_common/detouring/hde/include -isystem garrysmod_common/detouring/minhook/include -isystem garrysmod_common/sourcesdk-minimal/common -isystem garrysmod_common/sourcesdk-minimal/game/shared -isystem garrysmod_common/sourcesdk-minimal/public -isystem garrysmod_common/sourcesdk-minimal/game/client -isystem garrysmod_common/sourcesdk-minimal/public/tier0 -isystem garrysmod_common/sourcesdk-minimal/public/tier1 -isystem garrysmod_common/sourcesdk-minimal/public/mathlib
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

ifeq ($(config),releasewithsymbols_x86_64)
TARGETDIR = x86_64/ReleaseWithSymbols
TARGET = $(TARGETDIR)/gmcl_gwater2_linux64.dll
OBJDIR = x86_64/ReleaseWithSymbols/intermediate/gmcl_gwater2
DEFINES += -D_GLIBCXX_USE_CXX11_ABI=0 -DNDEBUG -DGMMODULE -DGWATER2_CLIENT -DIS_SERVERSIDE=false -DGMOD_ALLOW_OLD_TYPES -DGMOD_ALLOW_LIGHTUSERDATA -DGMOD_MODULE_NAME=\"gwater2\" -DCLIENT_DLL -DGMOD_USE_SOURCESDK -DRAD_TELEMETRY_DISABLED -DNO_STRING_T -DVECTOR -DVERSION_SAFE_STEAM_API_INTERFACES -DPROTECTED_THINGS_ENABLE -D_DLL_EXT=.so -DCOMPILER_GCC -DPOSIX -D_POSIX -DLINUX -D_LINUX -DGNUC -DSWDS -DPLATFORM_64BITS
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -Wshadow -Wundef -Og -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -g -msse2 -Wall -Wextra -std=gnu11 -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-undef -Wno-ignored-attributes -Wno-invalid-offsetof
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -Wshadow -Wundef -Og -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -g -msse2 -Wall -Wextra -std=gnu++17 -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-undef -Wno-ignored-attributes -Wno-invalid-offsetof
LIBS += garrysmod_common/projects/linux/gmake2/x86_64/ReleaseWithSymbols/libhelpers.a garrysmod_common/projects/linux/gmake2/x86_64/ReleaseWithSymbols/liblua_shared.a garrysmod_common/scanning/projects/linux/gmake2/x86_64/ReleaseWithSymbols/libscanning.a garrysmod_common/detouring/projects/linux/gmake2/x86_64/ReleaseWithSymbols/libdetouring.a garrysmod_common/detouring/projects/linux/gmake2/x86_64/ReleaseWithSymbols/libminhook.a garrysmod_common/detouring/projects/linux/gmake2/x86_64/ReleaseWithSymbols/libhde.a garrysmod_common/sourcesdk-minimal/projects/linux/gmake2/x86_64/ReleaseWithSymbols/libtier1.a garrysmod_common/sourcesdk-minimal/projects/linux/gmake2/x86_64/ReleaseWithSymbols/libLZMA.a garrysmod_common/sourcesdk-minimal/projects/linux/gmake2/x86_64/ReleaseWithSymbols/libmathlib.a -ldl -ltier0_client -lvstdlib_client -lNvFlexReleaseCUDA_x64.a -lNvFlexDeviceRelease_x64.a -lNvFlexExtReleaseCUDA_x64.a
LDDEPS += garrysmod_common/projects/linux/gmake2/x86_64/ReleaseWithSymbols/libhelpers.a garrysmod_common/projects/linux/gmake2/x86_64/ReleaseWithSymbols/liblua_shared.a garrysmod_common/scanning/projects/linux/gmake2/x86_64/ReleaseWithSymbols/libscanning.a garrysmod_common/detouring/projects/linux/gmake2/x86_64/ReleaseWithSymbols/libdetouring.a garrysmod_common/detouring/projects/linux/gmake2/x86_64/ReleaseWithSymbols/libminhook.a garrysmod_common/detouring/projects/linux/gmake2/x86_64/ReleaseWithSymbols/libhde.a garrysmod_common/sourcesdk-minimal/projects/linux/gmake2/x86_64/ReleaseWithSymbols/libtier1.a garrysmod_common/sourcesdk-minimal/projects/linux/gmake2/x86_64/ReleaseWithSymbols/libLZMA.a garrysmod_common/sourcesdk-minimal/projects/linux/gmake2/x86_64/ReleaseWithSymbols/libmathlib.a
ALL_LDFLAGS += $(LDFLAGS) -Lgarrysmod_common/sourcesdk-minimal/lib/public/linux64 -LFleX/lib/linux64 -L/usr/lib64 -m64 -shared -Wl,-soname=gmcl_gwater2_linux64.dll -Wl,--no-undefined

else ifeq ($(config),releasewithsymbols_x86)
TARGETDIR = x86/ReleaseWithSymbols
TARGET = $(TARGETDIR)/gmcl_gwater2_linux.dll
OBJDIR = x86/ReleaseWithSymbols/intermediate/gmcl_gwater2
DEFINES += -D_GLIBCXX_USE_CXX11_ABI=0 -DNDEBUG -DGMMODULE -DGWATER2_CLIENT -DIS_SERVERSIDE=false -DGMOD_ALLOW_OLD_TYPES -DGMOD_ALLOW_LIGHTUSERDATA -DGMOD_MODULE_NAME=\"gwater2\" -DCLIENT_DLL -DGMOD_USE_SOURCESDK -DRAD_TELEMETRY_DISABLED -DNO_STRING_T -DVECTOR -DVERSION_SAFE_STEAM_API_INTERFACES -DPROTECTED_THINGS_ENABLE -D_DLL_EXT=.so -DCOMPILER_GCC -DPOSIX -D_POSIX -DLINUX -D_LINUX -DGNUC -DSWDS
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -Wshadow -Wundef -Og -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -g -msse2 -Wall -Wextra -std=gnu11 -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-undef -Wno-ignored-attributes -Wno-invalid-offsetof
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -Wshadow -Wundef -Og -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -g -msse2 -Wall -Wextra -std=gnu++17 -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-undef -Wno-ignored-attributes -Wno-invalid-offsetof
LIBS += garrysmod_common/projects/linux/gmake2/x86/ReleaseWithSymbols/libhelpers.a garrysmod_common/projects/linux/gmake2/x86/ReleaseWithSymbols/liblua_shared.a garrysmod_common/scanning/projects/linux/gmake2/x86/ReleaseWithSymbols/libscanning.a garrysmod_common/detouring/projects/linux/gmake2/x86/ReleaseWithSymbols/libdetouring.a garrysmod_common/detouring/projects/linux/gmake2/x86/ReleaseWithSymbols/libminhook.a garrysmod_common/detouring/projects/linux/gmake2/x86/ReleaseWithSymbols/libhde.a garrysmod_common/sourcesdk-minimal/projects/linux/gmake2/x86/ReleaseWithSymbols/libtier1.a garrysmod_common/sourcesdk-minimal/projects/linux/gmake2/x86/ReleaseWithSymbols/libLZMA.a garrysmod_common/sourcesdk-minimal/projects/linux/gmake2/x86/ReleaseWithSymbols/libmathlib.a -ldl -ltier0 -lvstdlib
LDDEPS += garrysmod_common/projects/linux/gmake2/x86/ReleaseWithSymbols/libhelpers.a garrysmod_common/projects/linux/gmake2/x86/ReleaseWithSymbols/liblua_shared.a garrysmod_common/scanning/projects/linux/gmake2/x86/ReleaseWithSymbols/libscanning.a garrysmod_common/detouring/projects/linux/gmake2/x86/ReleaseWithSymbols/libdetouring.a garrysmod_common/detouring/projects/linux/gmake2/x86/ReleaseWithSymbols/libminhook.a garrysmod_common/detouring/projects/linux/gmake2/x86/ReleaseWithSymbols/libhde.a garrysmod_common/sourcesdk-minimal/projects/linux/gmake2/x86/ReleaseWithSymbols/libtier1.a garrysmod_common/sourcesdk-minimal/projects/linux/gmake2/x86/ReleaseWithSymbols/libLZMA.a garrysmod_common/sourcesdk-minimal/projects/linux/gmake2/x86/ReleaseWithSymbols/libmathlib.a
ALL_LDFLAGS += $(LDFLAGS) -Lgarrysmod_common/sourcesdk-minimal/lib/public/linux32 -L/usr/lib32 -m32 -shared -Wl,-soname=gmcl_gwater2_linux.dll -Wl,--no-undefined

else ifeq ($(config),release_x86_64)
TARGETDIR = x86_64/Release
TARGET = $(TARGETDIR)/gmcl_gwater2_linux64.dll
OBJDIR = x86_64/Release/intermediate/gmcl_gwater2
DEFINES += -D_GLIBCXX_USE_CXX11_ABI=0 -DNDEBUG -DGMMODULE -DGWATER2_CLIENT -DIS_SERVERSIDE=false -DGMOD_ALLOW_OLD_TYPES -DGMOD_ALLOW_LIGHTUSERDATA -DGMOD_MODULE_NAME=\"gwater2\" -DCLIENT_DLL -DGMOD_USE_SOURCESDK -DRAD_TELEMETRY_DISABLED -DNO_STRING_T -DVECTOR -DVERSION_SAFE_STEAM_API_INTERFACES -DPROTECTED_THINGS_ENABLE -D_DLL_EXT=.so -DCOMPILER_GCC -DPOSIX -D_POSIX -DLINUX -D_LINUX -DGNUC -DSWDS -DPLATFORM_64BITS
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -Wshadow -Wundef -flto -O3 -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -msse2 -Wall -Wextra -std=gnu11 -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-undef -Wno-ignored-attributes -Wno-invalid-offsetof
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -Wshadow -Wundef -flto -O3 -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -msse2 -Wall -Wextra -std=gnu++17 -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-undef -Wno-ignored-attributes -Wno-invalid-offsetof
LIBS += garrysmod_common/projects/linux/gmake2/x86_64/Release/libhelpers.a garrysmod_common/projects/linux/gmake2/x86_64/Release/liblua_shared.a garrysmod_common/scanning/projects/linux/gmake2/x86_64/Release/libscanning.a garrysmod_common/detouring/projects/linux/gmake2/x86_64/Release/libdetouring.a garrysmod_common/detouring/projects/linux/gmake2/x86_64/Release/libminhook.a garrysmod_common/detouring/projects/linux/gmake2/x86_64/Release/libhde.a garrysmod_common/sourcesdk-minimal/projects/linux/gmake2/x86_64/Release/libtier1.a garrysmod_common/sourcesdk-minimal/projects/linux/gmake2/x86_64/Release/libLZMA.a garrysmod_common/sourcesdk-minimal/projects/linux/gmake2/x86_64/Release/libmathlib.a -ldl -ltier0_client -lvstdlib_client FleX/lib/linux64/NvFlexReleaseCUDA_x64.a FleX/lib/linux64/NvFlexDeviceRelease_x64.a FleX/lib/linux64/NvFlexExtReleaseCUDA_x64.a
LDDEPS += garrysmod_common/projects/linux/gmake2/x86_64/Release/libhelpers.a garrysmod_common/projects/linux/gmake2/x86_64/Release/liblua_shared.a garrysmod_common/scanning/projects/linux/gmake2/x86_64/Release/libscanning.a garrysmod_common/detouring/projects/linux/gmake2/x86_64/Release/libdetouring.a garrysmod_common/detouring/projects/linux/gmake2/x86_64/Release/libminhook.a garrysmod_common/detouring/projects/linux/gmake2/x86_64/Release/libhde.a garrysmod_common/sourcesdk-minimal/projects/linux/gmake2/x86_64/Release/libtier1.a garrysmod_common/sourcesdk-minimal/projects/linux/gmake2/x86_64/Release/libLZMA.a garrysmod_common/sourcesdk-minimal/projects/linux/gmake2/x86_64/Release/libmathlib.a
ALL_LDFLAGS += $(LDFLAGS) -Lgarrysmod_common/sourcesdk-minimal/lib/public/linux64 -LFleX/lib/linux64 -L/usr/lib64 -m64 -flto -shared -Wl,-soname=gmcl_gwater2_linux64.dll -s -Wl,--no-undefined

else ifeq ($(config),release_x86)
TARGETDIR = x86/Release
TARGET = $(TARGETDIR)/gmcl_gwater2_linux.dll
OBJDIR = x86/Release/intermediate/gmcl_gwater2
DEFINES += -D_GLIBCXX_USE_CXX11_ABI=0 -DNDEBUG -DGMMODULE -DGWATER2_CLIENT -DIS_SERVERSIDE=false -DGMOD_ALLOW_OLD_TYPES -DGMOD_ALLOW_LIGHTUSERDATA -DGMOD_MODULE_NAME=\"gwater2\" -DCLIENT_DLL -DGMOD_USE_SOURCESDK -DRAD_TELEMETRY_DISABLED -DNO_STRING_T -DVECTOR -DVERSION_SAFE_STEAM_API_INTERFACES -DPROTECTED_THINGS_ENABLE -D_DLL_EXT=.so -DCOMPILER_GCC -DPOSIX -D_POSIX -DLINUX -D_LINUX -DGNUC -DSWDS
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -Wshadow -Wundef -flto -O3 -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -msse2 -Wall -Wextra -std=gnu11 -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-undef -Wno-ignored-attributes -Wno-invalid-offsetof
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -Wshadow -Wundef -flto -O3 -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -msse2 -Wall -Wextra -std=gnu++17 -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-undef -Wno-ignored-attributes -Wno-invalid-offsetof
LIBS += garrysmod_common/projects/linux/gmake2/x86/Release/libhelpers.a garrysmod_common/projects/linux/gmake2/x86/Release/liblua_shared.a garrysmod_common/scanning/projects/linux/gmake2/x86/Release/libscanning.a garrysmod_common/detouring/projects/linux/gmake2/x86/Release/libdetouring.a garrysmod_common/detouring/projects/linux/gmake2/x86/Release/libminhook.a garrysmod_common/detouring/projects/linux/gmake2/x86/Release/libhde.a garrysmod_common/sourcesdk-minimal/projects/linux/gmake2/x86/Release/libtier1.a garrysmod_common/sourcesdk-minimal/projects/linux/gmake2/x86/Release/libLZMA.a garrysmod_common/sourcesdk-minimal/projects/linux/gmake2/x86/Release/libmathlib.a -ldl -ltier0 -lvstdlib
LDDEPS += garrysmod_common/projects/linux/gmake2/x86/Release/libhelpers.a garrysmod_common/projects/linux/gmake2/x86/Release/liblua_shared.a garrysmod_common/scanning/projects/linux/gmake2/x86/Release/libscanning.a garrysmod_common/detouring/projects/linux/gmake2/x86/Release/libdetouring.a garrysmod_common/detouring/projects/linux/gmake2/x86/Release/libminhook.a garrysmod_common/detouring/projects/linux/gmake2/x86/Release/libhde.a garrysmod_common/sourcesdk-minimal/projects/linux/gmake2/x86/Release/libtier1.a garrysmod_common/sourcesdk-minimal/projects/linux/gmake2/x86/Release/libLZMA.a garrysmod_common/sourcesdk-minimal/projects/linux/gmake2/x86/Release/libmathlib.a
ALL_LDFLAGS += $(LDFLAGS) -Lgarrysmod_common/sourcesdk-minimal/lib/public/linux32 -L/usr/lib32 -m32 -flto -shared -Wl,-soname=gmcl_gwater2_linux.dll -s -Wl,--no-undefined

endif

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/ABICompatibility.o
GENERATED += $(OBJDIR)/BSPParser.o
GENERATED += $(OBJDIR)/BaseShader.o
GENERATED += $(OBJDIR)/Displacements.o
GENERATED += $(OBJDIR)/GMFS.o
GENERATED += $(OBJDIR)/NormalBlending.o
GENERATED += $(OBJDIR)/Parser.o
GENERATED += $(OBJDIR)/SubEdgeIterator.o
GENERATED += $(OBJDIR)/TBNGen.o
GENERATED += $(OBJDIR)/UVGen.o
GENERATED += $(OBJDIR)/Vector.o
GENERATED += $(OBJDIR)/Vector2D.o
GENERATED += $(OBJDIR)/flex_solver.o
GENERATED += $(OBJDIR)/interfaces.o
GENERATED += $(OBJDIR)/main.o
GENERATED += $(OBJDIR)/mesh.o
GENERATED += $(OBJDIR)/meshutils_x64fix.o
OBJECTS += $(OBJDIR)/ABICompatibility.o
OBJECTS += $(OBJDIR)/BSPParser.o
OBJECTS += $(OBJDIR)/BaseShader.o
OBJECTS += $(OBJDIR)/Displacements.o
OBJECTS += $(OBJDIR)/GMFS.o
OBJECTS += $(OBJDIR)/NormalBlending.o
OBJECTS += $(OBJDIR)/Parser.o
OBJECTS += $(OBJDIR)/SubEdgeIterator.o
OBJECTS += $(OBJDIR)/TBNGen.o
OBJECTS += $(OBJDIR)/UVGen.o
OBJECTS += $(OBJDIR)/Vector.o
OBJECTS += $(OBJDIR)/Vector2D.o
OBJECTS += $(OBJDIR)/flex_solver.o
OBJECTS += $(OBJDIR)/interfaces.o
OBJECTS += $(OBJDIR)/main.o
OBJECTS += $(OBJDIR)/mesh.o
OBJECTS += $(OBJDIR)/meshutils_x64fix.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking gmcl_gwater2
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning gmcl_gwater2
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(GENERATED)) del /s /q $(subst /,\\,$(GENERATED))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/BSPParser.o: BSPParser/BSPParser.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Displacements.o: BSPParser/Displacements/Displacements.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/NormalBlending.o: BSPParser/Displacements/NormalBlending.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SubEdgeIterator.o: BSPParser/Displacements/SubEdgeIterator.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/TBNGen.o: BSPParser/Displacements/TBNGen.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/UVGen.o: BSPParser/Displacements/UVGen.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Parser.o: BSPParser/FileFormat/Parser.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Vector.o: BSPParser/FileFormat/Vector.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Vector2D.o: BSPParser/FileFormat/Vector2D.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/GMFS.o: GMFS/GMFS.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/BaseShader.o: src/BaseShader.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/flex_solver.o: src/flex_solver.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/main.o: src/main.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/mesh.o: src/mesh.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/meshutils_x64fix.o: src/meshutils_x64fix.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ABICompatibility.o: garrysmod_common/source/ABICompatibility.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/interfaces.o: garrysmod_common/sourcesdk-minimal/interfaces/interfaces.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif
