// ALL SKIP STATEMENTS THAT AFFECT THIS SHADER!!!
// defined $LIGHTING_PREVIEW && defined $FASTPATH && $LIGHTING_PREVIEW && $FASTPATH

#pragma once
#include "shaderlib/cshader.h"
class GWaterNormals_vs30_Static_Index
{
public:
	GWaterNormals_vs30_Static_Index( )
	{
	}

	int GetIndex() const
	{
		return 0;
	}
};

#define shaderStaticTest_GWaterNormals_vs30 1


class GWaterNormals_vs30_Dynamic_Index
{
public:
	GWaterNormals_vs30_Dynamic_Index( )
	{
	}

	int GetIndex() const
	{
		return 0;
	}
};

#define shaderDynamicTest_GWaterNormals_vs30 1

