#pragma once
#include "shaderlib/cshader.h"
class GWaterSmooth_ps30_Static_Index
{
public:
	GWaterSmooth_ps30_Static_Index( )
	{
	}

	int GetIndex() const
	{
		return 0;
	}
};

#define shaderStaticTest_GWaterSmooth_ps30 1


class GWaterSmooth_ps30_Dynamic_Index
{
public:
	GWaterSmooth_ps30_Dynamic_Index( )
	{
	}

	int GetIndex() const
	{
		return 0;
	}
};

#define shaderDynamicTest_GWaterSmooth_ps30 1

