#pragma once
#include "shaderlib/cshader.h"
class GWaterNormals_ps30_Static_Index
{
public:
	GWaterNormals_ps30_Static_Index( )
	{
	}

	int GetIndex() const
	{
		return 0;
	}
};

#define shaderStaticTest_GWaterNormals_ps30 1


class GWaterNormals_ps30_Dynamic_Index
{
public:
	GWaterNormals_ps30_Dynamic_Index( )
	{
	}

	int GetIndex() const
	{
		return 0;
	}
};

#define shaderDynamicTest_GWaterNormals_ps30 1

