#pragma once
#include "shaderlib/cshader.h"
class GWaterNormalsCheap_ps30_Static_Index
{
public:
	GWaterNormalsCheap_ps30_Static_Index( )
	{
	}

	int GetIndex() const
	{
		return 0;
	}
};

#define shaderStaticTest_GWaterNormalsCheap_ps30 1


class GWaterNormalsCheap_ps30_Dynamic_Index
{
public:
	GWaterNormalsCheap_ps30_Dynamic_Index( )
	{
	}

	int GetIndex() const
	{
		return 0;
	}
};

#define shaderDynamicTest_GWaterNormalsCheap_ps30 1

