#pragma once
#include "shaderlib/cshader.h"
class GWaterFinalpass_ps30_Static_Index
{
public:
	GWaterFinalpass_ps30_Static_Index( )
	{
	}

	int GetIndex() const
	{
		return 0;
	}
};

#define shaderStaticTest_GWaterFinalpass_ps30 1


class GWaterFinalpass_ps30_Dynamic_Index
{
public:
	GWaterFinalpass_ps30_Dynamic_Index( )
	{
	}

	int GetIndex() const
	{
		return 0;
	}
};

#define shaderDynamicTest_GWaterFinalpass_ps30 1

